#######################################################################################
# A default configuration that will be loaded for all jupyter books
# Users are expected to override these values in their own `_config.yml` file.
# This is also the "master list" of all allowed keys and values.

#######################################################################################
title: "" # The title of the book. Will be placed in the left navbar.
author: Nikolay Iskrev # The author of the book
copyright: '2022' # Copyright year to be placed in the footer
logo: '_static/images/logo.png' # A path to the book logo
description: Website for Econ 108
#######################################################################################

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

only_build_toc_files: true
execute:
  execute_notebooks: "cache"
  timeout: 600

bibtex_bibfiles:
   - _static/econ108.bib

html:
  baseurl: https://niskrev.github.io/econ108/

latex:
   latex_documents:
      targetname: econ108.tex

sphinx:
  extra_extensions: [sphinx_multitoc_numbering, sphinxext.rediraffe, sphinx_tojupyter, sphinxcontrib.youtube, sphinx.ext.todo]
  config:
    nb_render_priority:
      html:
      - "application/vnd.jupyter.widget-view+json"
      - "application/javascript"
      - "text/html"
      - "text/latex"
      - "image/svg+xml"
      - "image/png"
      - "image/jpeg"
      - "text/markdown"
      - "text/plain"
      jupyter:
      - "application/vnd.jupyter.widget-view+json"
      - "application/javascript"
      - "text/html"
      - "text/latex"
      - "image/svg+xml"
      - "image/png"
      - "image/jpeg"
      - "text/markdown"
      - "text/plain"
    html_favicon: _static/lectures-favicon.ico
    html_static_path: ['_static']
    mathjax3_config:
      tex:
        macros:
          "argmax" : "arg\\,max"
          "argmin" : "arg\\,min"
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-svg.js
    rediraffe_redirects:
      index_toc.md: index.md
    tojupyter_static_file_path: ["source/_static", "_static"]
    tojupyter_target_html: true
    tojupyter_lang_synonyms: ["ipython", "ipython3", "python"]
    tojupyter_images_markdown: true